version: '3.9'

services:
  oracle:
    image: gvenzl/oracle-free:slim
    container_name: oracle-local
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init-schema.sql:/container-entrypoint-initdb.d/init-schema.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  wildfly:
    image: quay.io/wildfly/wildfly:latest-jdk21
    container_name: wildfly-local
    depends_on:
      oracle:
        condition: service_healthy
    ports:
      - "8180:8080"
      - "9990:9990"
    volumes:
      - ./target/corporate-fleet-manager.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war
      # crée un fichier vide qui sera copié comme ROOT.war.dodeploy pour forcer le déploiement immédiat
      - ./deploy-trigger:/opt/jboss/wildfly/standalone/deployments/ROOT.war.dodeploy:ro

volumes:
  oracle-data: