services:
  oracle:
    image: gvenzl/oracle-free:slim
    container_name: oracle-local
    ports:
      - "15210:1521"
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init-schema.sql:/container-entrypoint-initdb.d/init-schema.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  wildfly:
    image: quay.io/wildfly/wildfly:latest-jdk21
    container_name: wildfly-local
    depends_on:
      oracle:
        condition: service_healthy
    ports:
      - "8180:8080"
      - "19990:9990"
    #    volumes:
    #      - ./target/corporate-fleet-manager.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war
    command: >
      /bin/bash -c "
      /opt/jboss/wildfly/bin/add-user.sh admin admin --silent &&
      /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
      "

volumes:
  oracle-data: